# Generated by Django 3.1.4 on 2021-02-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='name',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
